### ISSUE TITLE
Login fails with Exception "property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given"

### ISSUE THREAD

**Issue by bllngr** [nextcloud/user_oidc#1073]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Enable Synology DSM SSO Server for OIDC, and add an application for Nextcloud (see "Additional information" below)
2. Configure the oidc plugin as shown below.
3. Add a Nextcloud user with the same username as an existing DSM user
3. Open the Nextcloud login page, and press the OIDC button.
4. The Synology SSO login page opens.
5. Login with the DSM user credentials

### Expected behaviour
Login succeeds, or fails with a descriptive error message.

### Actual behaviour
* Login fails
* Nextcloud shows generic error message "Internal Server Error"
  * The server was unable to complete your request.  
     If this happens again, please send the technical details below to the server administrator.  
     More details can be found in the server log.
* Nextcloud logs the mentioned exception
  <details>
  <summary>Expand to show error message log</summary>
  <pre>{"reqId":"pMWJiJPPhuVq9jSzQydx","level":3,"time":"2025-03-08T17:54:04+00:00","remoteAddr":"188.174.170.45","user":"--","app":"index","method":"GET","url":"/apps/oidc_login/oidc?code=ND6ZvxhbuH9ucE0dgKA9RG2llHuHkj0R&state=13c5b4ad48fe47559ef02f34dba0a3ba","message":"property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in file '/var/www/html/custom_apps/oidc_login/3rdparty/jumbojett/openid-connect-php/src/OpenIDConnectClient.php' line 343","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0","version":"30.0.6.2","exception":{"Exception":"Exception","Message":"property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in file '/var/www/html/custom_apps/oidc_login/3rdparty/jumbojett/openid-connect-php/src/OpenIDConnectClient.php' line 343","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\OIDCLogin\\Controller\\LoginController"},"oidc"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\OIDCLogin\\Controller\\LoginController","oidc",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"oidc_login.login.oidc"}]},{"file":"/var/www/html/lib/base.php","line":1003,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/oidc_login/oidc"]},{"file":"/var/www/html/index.php","line":24,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":146,"Previous":{"Exception":"TypeError","Message":"property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/oidc_login/3rdparty/jumbojett/openid-connect-php/src/OpenIDConnectClient.php","line":343,"function":"property_exists","args":[null,"id_token"]},{"file":"/var/www/html/custom_apps/oidc_login/lib/Controller/LoginController.php","line":58,"function":"authenticate","class":"Jumbojett\\OpenIDConnectClient","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":208,"function":"oidc","class":"OCA\\OIDCLogin\\Controller\\LoginController","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":114,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\OIDCLogin\\Controller\\LoginController"},"oidc"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\OIDCLogin\\Controller\\LoginController"},"oidc"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\OIDCLogin\\Controller\\LoginController","oidc",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"oidc_login.login.oidc"}]},{"file":"/var/www/html/lib/base.php","line":1003,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/oidc_login/oidc"]},{"file":"/var/www/html/index.php","line":24,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/custom_apps/oidc_login/3rdparty/jumbojett/openid-connect-php/src/OpenIDConnectClient.php","Line":343},"message":"property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in file '/var/www/html/custom_apps/oidc_login/3rdparty/jumbojett/openid-connect-php/src/OpenIDConnectClient.php' line 343","exception":{},"CustomMessage":"property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in file '/var/www/html/custom_apps/oidc_login/3rdparty/jumbojett/openid-connect-php/src/OpenIDConnectClient.php' line 343"}}</pre>
  </details>
* This might very well be a configuration issue on my side, but with the given feedback, there's not much I can work out.

### Server configuration

**Web server:** Apache (nextcloud:30.0.6-apache docker image)

**Database:** MariaDB 10.11.11

**PHP version:** 8.2.27

**Nextcloud version:** Nextcloud Hub 9 (30.0.6) (Docker image)

<details>
<summary>List of activated apps</summary>

```
Enabled:                                                                                                                                
  - activity: 3.0.0                                                                                                                     
  - app_api: 4.0.6                                                                                                                      
  - bruteforcesettings: 3.0.0                                                                                                           
  - cloud_federation_api: 1.13.0                                                                                                        
  - dav: 1.31.1                                                                                                                         
  - federatedfilesharing: 1.20.0                                                                                                        
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_external: 1.22.0                                                                                                              
  - files_pdfviewer: 3.0.0                                                                                                              
  - files_reminders: 1.3.0                                                                                                              
  - files_retention: 1.19.0                                                                                                             
  - files_sharing: 1.22.0                                                                                                               
  - files_trashbin: 1.20.1                                                                                                              
  - files_versions: 1.23.0                                                                                                              
  - groupfolders: 18.1.0                                                                                                                
  - logreader: 3.0.0                                                                                                                    
  - lookup_server_connector: 1.18.0                                                                                                     
  - nextcloud_announcements: 2.0.0                                                                                                      
  - notifications: 3.0.0                                                                                                                
  - oauth2: 1.18.1                                                                                                                      
  - oidc_login: 3.2.2                                                                                                                   
  - password_policy: 2.0.0                                                                                                              
  - photos: 3.0.2                                                                                                                       
  - previewgenerator: 5.8.0                                                                                                             
  - provisioning_api: 1.20.0                                                                                                            
  - related_resources: 1.5.0                                                                                                            
  - serverinfo: 2.0.0                                                                                                                   
  - settings: 1.13.0                                                                                                                    
  - sharebymail: 1.20.0                                                                                                                 
  - survey_client: 2.0.0                                                                                                                
  - text: 4.1.0                                                                                                                         
  - theming: 2.6.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_totp: 12.0.0-dev
  - updatenotification: 1.20.0
  - viewer: 3.0.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - admin_audit: 1.20.0
  - circles: 30.0.0 (installed 25.0.0)
  - comments: 1.20.1 (installed 1.4.0)
  - contactsinteraction: 1.11.0 (installed 1.1.0)
  - dashboard: 7.10.0 (installed 7.0.0)
  - encryption: 2.18.0
  - federation: 1.20.0 (installed 1.5.0)
  - files_automatedtagging: 1.16.1 (installed 1.16.1)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 3.0.0 (installed 2.3.0)
  - privacy: 2.0.0 (installed 1.3.0)
  - recommendations: 3.0.0 (installed 0.8.0)
  - support: 2.0.0 (installed 1.0.0)
  - suspicious_login: 8.0.0
  - systemtags: 1.20.0 (installed 1.4.0)
  - twofactor_nextcloud_notification: 4.0.0
  - user_ldap: 1.21.0
  - user_saml: 5.2.4 (installed 5.2.4)
  - user_status: 1.10.0 (installed 1.6.0)
  - weather_status: 1.10.0 (installed 1.0.0)
  - workflow_ocr: 1.26.1 (installed 1.26.1)
  - workflow_script: 1.11.1 (installed 1.11.1)
```
</details>

<details>
<summary>Nextcloud configuration</summary>

```
{                                                                                                                                       
    "system": {                                                                                                                         
        "htaccess.RewriteBase": "\/",                                                                                                   
        "memcache.local": "\\OC\\Memcache\\APCu",                                                                                       
        "memcache.locking": "\\OC\\Memcache\\Redis",                                                                                    
        "filelocking.enabled": "true",                                                                                                  
        "redis": {                                                                                                                      
            "host": "***REMOVED SENSITIVE VALUE***",                                                                                    
            "port": 6379                                                                                                                
        },                                                                                                                              
        "apps_paths": [                                                                                                                 
            {                                                                                                                           
                "path": "\/var\/www\/html\/apps",                                                                                       
                "url": "\/apps",                                                                                                        
                "writable": false                                                                                                       
            },                                                                                                                          
            {                                                                                                                           
                "path": "\/var\/www\/html\/custom_apps",                                                                                
                "url": "\/custom_apps",                                                                                                 
                "writable": true                                                                                                        
            }                                                                                                                           
        ],
        "preview_max_x": 2160,
        "preview_max_y": 2160,
        "preview_max_scale_factor": 1,
        "preview_max_filesize_image": 32,
        "preview_max_memory": 256, 
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "diskstation.local:8080",
            "<redacted>"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "<redacted>",
        "overwrite.cli.url": "https:\/\/<redacted>",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "30.0.6.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 1,
        "log_type": "file",
        "maintenance": false,
        "updater.release.channel": "enterprise",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "7, 30",
        "memories.exiftool": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.index.mode": "0",
        "lost_password_link": "disabled",
        "oidc_login_provider_url": "https:\/\/diskstation\/webman\/sso",
        "oidc_login_client_id": "<redacted>",
        "oidc_login_client_secret": "<redacted>",
        "oidc_login_end_session_redirect": false,
        "oidc_login_auto_redirect": false,
        "oidc_login_redir_fallback": true,
        "oidc_login_attributes": {
            "id": "username", // the same with `preferred_username`
            "mail": "email"
        },
        "oidc_login_use_id_token": true, // the same with `false`
        "oidc_login_scope": "openid profile",
        "oidc_login_tls_verify": false
    }
}
```
</details>

### Additional information

* Application settings in DSM SSO Server configuration:
  * Redirect URL: https://\<overwritehost\>/apps/oidc_login/oidc
  * Protocol: OIDC
* DSM SSO Server log:
  ```
  User [bllngr] signed in to application [Nextcloud] via SSO
  ```
* It used to work using this configuration ~a year ago, but I can't remember which NC & `user_oidc` app version I was using back then.
