### ISSUE TITLE
Default 'client_secret_basic' breaks Nextcloud with Authelia

### ISSUE THREAD

**Issue by krair** [nextcloud/user_oidc#907]
After updating to `user_oidc` version 6.0.0, I am locked out of my Nextcloud instance. I am using Authelia 4.38.9 as my OIDC provider. I am getting the following error message:

```
time="2024-07-29T13:55:26Z" level=error msg="Access Request failed with error: Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). The request was determined to be using 'token_endpoint_auth_method' method 'client_secret_basic', however the OAuth 2.0 client registration does not allow this method. The registered client with id 'xxxxxxx' is configured to only support 'token_endpoint_auth_method' method 'client_secret_post'. Either the Authorization Server client registration will need to have the 'token_endpoint_auth_method' updated to 'client_secret_basic' or the Relying Party will need to be configured to use 'client_secret_post'." method=POST path=/api/oidc/token remote_ip=192.168.2.1

```

![Screenshot from 2024-07-29 15-56-53](https://github.com/user-attachments/assets/3064ae77-a4c3-468c-8850-b4e02bd7aa78)

Authelia is set to use the `client_secret_post` method. Here's the relevant part of the config file:

```
      - client_id: 'xxxxxxxxxxxx'
        client_name: 'NextCloud'
        client_secret: 'xxxxxxxxxxxx'
        public: false
        authorization_policy: 'two_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'https://cloud.domain.tld/apps/user_oidc/code'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
        consent_mode: 'implicit'
```

I believe this is related to https://github.com/nextcloud/user_oidc/pull/897
